import './globals.css'
import type { Metadata } from 'next'
import { gilroy } from '@/fonts/fonts'
import NavBar from '@/components/nav-bar'

// Google Font
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={gilroy.variable}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
